# Generated by Django 5.1.6 on 2025-05-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True)),
                ('bio', models.TextField(blank=True)),
                ('specilization', models.CharField(choices=[('dentist', 'dentist'), ('physician', 'physician'), ('cardiologist', 'cardiologist'), ('ent', 'ent')], max_length=300)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('profile_status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], max_length=100)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
