# Generated by Django 5.1.6 on 2025-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0002_dprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
