# Generated by Django 5.2.1 on 2025-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0004_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='treatment_status',
            field=models.CharField(choices=[('completed', 'completed'), ('absent', 'absent'), ('pending', 'pending')], default='pending', max_length=100),
        ),
    ]
