# Generated by Django 5.2.1 on 2025-06-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0005_bookings_treatment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='profile_status',
            field=models.CharField(choices=[('aproved', 'aproved'), ('rejected', 'rejected')], max_length=100),
        ),
    ]
