# Generated by Django 5.2.1 on 2025-06-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0006_alter_dprofile_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpro',
            name='profile_photo',
            field=models.ImageField(default='patient_photos/default.png', upload_to='patient_photos/'),
        ),
        migrations.AlterField(
            model_name='dprofile',
            name='profile_status',
            field=models.CharField(choices=[('aproved', 'aproved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=100),
        ),
    ]
