# Generated by Django 5.2.1 on 2025-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0007_patientpro_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpro',
            name='profile_photo',
            field=models.ImageField(upload_to='patient_photos/'),
        ),
    ]
