# Generated by Django 5.2.1 on 2025-06-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0008_alter_patientpro_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpro',
            name='profile_photo',
            field=models.ImageField(upload_to='patient_photos'),
        ),
    ]
