# Generated by Django 5.2.1 on 2025-06-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0010_alter_patientpro_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientpro',
            name='profile_photo',
        ),
    ]
