# Generated by Django 5.2.1 on 2025-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0011_remove_patientpro_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpro',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
