# Generated by Django 5.2.1 on 2025-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0012_patientpro_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpro',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos'),
        ),
    ]
