# Generated by Django 5.2.1 on 2025-06-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0013_alter_patientpro_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprofile',
            name='clinic_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dprofile',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dprofile',
            name='consultation_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dprofile',
            name='consultation_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_photos/'),
        ),
        migrations.AddField(
            model_name='dprofile',
            name='qualifications',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dprofile',
            name='specilization',
            field=models.CharField(choices=[('dentist', 'dentist'), ('cardiologist', 'cardiologist'), ('ent', 'ent')], max_length=300),
        ),
        migrations.AlterField(
            model_name='patientpro',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
