# Generated by Django 5.2.1 on 2025-06-27 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0014_dprofile_clinic_address_dprofile_clinic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprofile',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientpro',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
