# Generated by Django 5.2.1 on 2025-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0015_dprofile_created_patientpro_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='consultation_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
