# Generated by Django 5.2.1 on 2025-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0016_alter_dprofile_consultation_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
