# Generated by Django 5.2.1 on 2025-06-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0017_alter_dprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_photos/'),
        ),
    ]
