# Generated by Django 5.2.1 on 2025-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0018_alter_dprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='specilization',
            field=models.CharField(blank=True, choices=[('dentist', 'dentist'), ('cardiologist', 'cardiologist'), ('ent', 'ent')], max_length=300),
        ),
    ]
