# Generated by Django 5.2.1 on 2025-06-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0020_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookings',
            name='Phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
