# Generated by Django 5.2.1 on 2025-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0021_bookings_email_bookings_name_bookings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Name',
            field=models.CharField(blank=True, default='your name', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='Phone',
            field=models.CharField(default='contact number', max_length=12, null=True),
        ),
    ]
