# Generated by Django 5.2.1 on 2025-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0022_alter_bookings_name_alter_bookings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='Name',
            field=models.CharField(blank=True, default='your name', max_length=50, null=True),
        ),
    ]
