# Generated by Django 5.2.1 on 2025-07-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookadoc', '0023_alter_bookings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dprofile',
            name='specilization',
            field=models.CharField(blank=True, choices=[('dentist', 'dentist'), ('cardiologist', 'cardiologist'), ('otolaryngologist', 'otolaryngologist'), ('orthopedist', 'orthopedist'), ('pediatrics', 'pediatrics'), ('ophthalmologist', 'ophthalmologist'), ('gynecologist', 'gynecologist'), ('dermatologist', 'dermatologist'), ('neurologist', 'neurologist'), ('psychiatrist', 'psychiatrist')], max_length=300),
        ),
    ]
